RamadanBags.Web/Controllers/SecurityController.cs
using EGIC.Core.Domain.Users;
using EGIC.Core.Models.Security;
using EGIC.Core.Models.Users;
using Microsoft.AspNetCore.Mvc;
using RamadanBags.Services.Authentication;
using System;

namespace RamadanBags.Web.Controllers
{
    public class SecurityController : BaseController
    {
        #region Fields

        private readonly IAuthenticationService _authenticationService;

        #endregion

        #region CTOR

        public SecurityController(
            IServiceProvider service,
            IAuthenticationService authenticationService) : base(service)
        {
            _authenticationService = authenticationService;
        }

        #endregion

        #region Utilities


        #endregion

        #region Actions

        #region Login/Logout

        [Route("/login")]
        public IActionResult Login()
        {
            var model = new LoginModel();
            return View(model);
        }

        [HttpPost]
        [Route("/login")]
        public virtual IActionResult Login(LoginModel model, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                model.Username = model.Username.Trim().ToUpper();
                var loginResult = _authenticationService.ValidateUser(model.Username, model.Password, out User user);
                switch (loginResult)
                {
                    case UserLoginResults.Successful:
                        {


                            //sign in new user
                            _authenticationService.SignIn(user);

                            if (string.IsNullOrEmpty(returnUrl) || !Url.IsLocalUrl(returnUrl))
                                return RedirectToAction("Index", "Home");

                            return Redirect(returnUrl);
                        }
                    case UserLoginResults.UserNotExist:
                        ModelState.AddModelError("", "هذا المُستخدم غير موجود");
                        break;
                    case UserLoginResults.Deleted:
                        ModelState.AddModelError("", "تم ايقاف هذا المُستخدم");
                        break;
                    case UserLoginResults.WrongPassword:
                    default:
                        ModelState.AddModelError("", "من فضلك تأكد من كلمة المرور, وأعد المحاولة.");//
                        break;
                }
            }

            return View(model);
        }

        [Route("/logout")]
        public virtual IActionResult Logout()
        {
            //standard logout 
            _authenticationService.SignOut();

            return RedirectToAction("Login");
        }

        #endregion

        public virtual IActionResult AccessDenied(string pageUrl)
        {
            var currentUser = _workContext.CurrentUser;
            return View();
        }

        #endregion
    }
}

RamadanBags.Web/Views/Shared/Confirm.cshtml
@model ActionConfirmationModel
@using EGIC.Web.Framework.Mvc.Models
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="@(Model.WindowId)-title">
                رسالة تأكيد
            </h4>
        </div>
        <div class="modal-body">
            @Model.Message
        </div>
        <div class="modal-footer">
            <button type="submit" id="@(Model.WindowId)-submit-button" class="btn btn-danger pull-right">
                نعم
            </button>
            <span class="btn btn-default pull-right margin-r-5" data-dismiss="modal">
                لا
            </span>
        </div>
    </div>
</div>

RamadanBags.Web/Views/Shared/Delete.cshtml
@model DeleteConfirmationModel
@using EGIC.Web.Framework.Mvc.Models
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="@(Model.WindowId)-title">
                رسالة تأكيد
            </h4>
        </div>
        <form asp-action="@Model.ActionName" asp-controller="@Model.ControllerName" asp-route-code="@Model.Code">
            <div class="form-horizontal">
                <div class="modal-body danger">
                    @Model.Message
                </div>
                <div class="modal-footer">
                    <span class="btn btn-default" data-dismiss="modal">
                        إلغاء
                    </span>
                    <button type="submit" class="btn btn-danger pull-right">
                        موافق
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>

RamadanBags.Web/Views/Shared/Menu.cshtml
@using EGIC.Web.Framework.Menu
@{
    var items = new List<SiteMapNode>
{
new SiteMapNode
{
    SystemName = "Home",
    IconClass = "fa-desktop",
    Title = "الرئيسية",
    ActionName = "Index",
    ControllerName = "Home",
    Visible = true
},
new SiteMapNode
{
    SystemName = "RamadanBags/Add",
    IconClass = "fa-plus",
    Title = "تسليم شنطة رمضان",
    ActionName = "Add",
    ControllerName = "RamadanBags",
    Visible = true
},
new SiteMapNode
{
    SystemName = "RamadanBags",
    IconClass = "fa-gift",
    Title = "عرض شنط رمضان",
    ActionName = "Index",
    ControllerName = "RamadanBags",
    Visible = true
}
    };
}
<ul class="sidebar-menu">
    @foreach (var item in items.Where(x => x.Visible))
    {
        @await Html.PartialAsync("_MenuItem", item)
    }
</ul>

RamadanBags.Web/Views/Shared/Notifications.cshtml
@using EGIC.Web.Framework.UI
@{
    //success messages
    var successMessages = new List<string>();
    if (TempData[$"egic.notifications.{NotifyType.Success}"] != null)
    {
        successMessages.AddRange(TempData[$"egic.notifications.{NotifyType.Success}"] as IList<string>);
    }
    if (ViewData[$"egic.notifications.{NotifyType.Success}"] != null)
    {
        successMessages.AddRange(ViewData[$"egic.notifications.{NotifyType.Success}"] as IList<string>);
    }


    //error messages
    var errorMessages = new List<string>();
    if (TempData[$"egic.notifications.{NotifyType.Error}"] != null)
    {
        errorMessages.AddRange(TempData[$"egic.notifications.{NotifyType.Error}"] as IList<string>);
    }
    if (ViewData[$"egic.notifications.{NotifyType.Error}"] != null)
    {
        errorMessages.AddRange(ViewData[$"egic.notifications.{NotifyType.Error}"] as IList<string>);
    }


    //warning messages
    var warningMessages = new List<string>();
    if (TempData[$"egic.notifications.{NotifyType.Warning}"] != null)
    {
        warningMessages.AddRange(TempData[$"egic.notifications.{NotifyType.Warning}"] as IList<string>);
    }
    if (ViewData[$"egic.notifications.{NotifyType.Warning}"] != null)
    {
        warningMessages.AddRange(ViewData[$"egic.notifications.{NotifyType.Warning}"] as IList<string>);
    }
}

@foreach (var message in successMessages)
{
    @*<div class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            @message
        </div>*@

    <div class="alert alert-success alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <h4><i class="icon fa fa-check"></i> تم بنجاح</h4>
        @Html.Raw(message)
    </div>
}

@foreach (var message in errorMessages)
{

    @*<div class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        @message
    </div>*@

    <div class="alert alert-danger alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <h4><i class="icon fa fa-stop"></i>خطأ!</h4>
        @Html.Raw(message)
    </div>
}

@foreach (var message in warningMessages)
{
    @*<div class="alert alert-warning alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            @message
        </div>*@

    <div class="alert alert-warning alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <h4><i class="icon fa fa-warning"></i> تنبيه!</h4>
        @Html.Raw(message)
    </div>
}

RamadanBags.Web/Views/Shared/_AddCustomePicture.cshtml
@model EGIC.Core.Models.RamadanBags.RamadanBagModel
@using RamadanBags.Services.RamadanBags;
@inject IRamadanBagService _ramadanBagService
@{
    string defaultImageUrl = _ramadanBagService.GetDefaultPictureUrl().Replace("\\", "/");
}
<script src="~/lib/compressjs/compressjs.js"></script>
<div class="row">
    <div class="col-md-6 col-sm-12">
        <div class="form-group">
            <div class="col-md-12">
                <egic-label asp-for="@Model.ID_FrontImagePath" style="float:none!important;" />
                <br />
                <img src="@(string.IsNullOrWhiteSpace(Model.ID_FrontImagePath)?defaultImageUrl:Model.ID_FrontImagePath)" width="150" id="previewFront" /> <br />
                <input type="file" id="uploadFront" style="display:inline-block;"/>
                <i id="spinnerFront" class="fa fa-spinner fa-spin fa-2x text-success" style="display:none;"></i>
                <input type="hidden" asp-for="ID_FrontImagePath" />
                <span asp-validation-for="@Model.ID_FrontImagePath"></span>
            </div>
        </div>
    </div>
    <div class="col-md-6 col-sm-12">
        <div class="form-group">
            <div class="col-md-12">
                <egic-label asp-for="@Model.ID_RearImagePath" style="float:none!important;" />
                <br />
                <img src="@(string.IsNullOrWhiteSpace(Model.ID_RearImagePath)?defaultImageUrl:Model.ID_RearImagePath)" width="150" id="previewRear" /> <br />
                <input type="file" id="uploadRear" style="display:inline-block;" />
                <i id="spinnerRear" class="fa fa-spinner fa-spin fa-2x text-success" style="display:none;"></i>
                <input type="hidden" asp-for="ID_RearImagePath" />
                <span asp-validation-for="@Model.ID_RearImagePath"></span>
            </div>
        </div>
    </div>
</div>
<script>
    $(function () {
        const compress = new Compress()
        const previewFront = document.getElementById('previewFront');
        const spinnerFront = $('#spinnerFront');

        const uploadFront = document.getElementById('uploadFront')
        const ID_Front = document.getElementById('ID_FrontImagePath')


        uploadFront.addEventListener('change', (evt) => {
            spinnerFront.show();
            const files = [...evt.target.files]
            compress.compress(files, {
                size: 0.5, // the max size in MB, defaults to 2MB
                quality: 0.75, // the quality of the image, max is 1,
                maxWidth: 950, // the max width of the output image, defaults to 1920px
                maxHeight: 600, // the max height of the output image, defaults to 1920px
                resize: true // defaults to true, set false if you do not want to resize the image width and height
            }).then((images) => {
                const img = images[0]
                // returns an array of compressed images
                let imgUrl = `${img.prefix}${img.data}`;
                previewFront.src = imgUrl;
                ID_Front.value = imgUrl;
                ID_Front.attributes['value'] = imgUrl;
                spinnerFront.hide();
            })
        }, false);


        const previewRear = document.getElementById('previewRear');
        const spinnerRear = $('#spinnerRear');

        const uploadRear = document.getElementById('uploadRear')
        const ID_Rear = document.getElementById('ID_RearImagePath')


        uploadRear.addEventListener('change', (evt) => {
            spinnerRear.show();
            const files = [...evt.target.files]
            compress.compress(files, {
                size: 0.5, // the max size in MB, defaults to 2MB
                quality: 0.75, // the quality of the image, max is 1,
                maxWidth: 950, // the max width of the output image, defaults to 1920px
                maxHeight: 600, // the max height of the output image, defaults to 1920px
                resize: true // defaults to true, set false if you do not want to resize the image width and height
            }).then((images) => {
                const img = images[0]
                // returns an array of compressed images
                let imgUrl = `${img.prefix}${img.data}`;
                previewRear.src = imgUrl;
                ID_Rear.value = imgUrl;
                ID_Rear.attributes['value'] = imgUrl;
                spinnerRear.hide();
            })
        }, false);
    });
</script>

RamadanBags.Web/Views/Shared/_AddPicture.cshtml
@model EGIC.Core.Models.RamadanBags.RamadanBagModel

<link href="~/lib/fineuploader/fineuploader-4.2.2.min.css" rel="stylesheet" />
<script src="~/lib/fineuploader/jquery.fineuploader-4.2.2.min.js"></script>

<div class="row">
    <div class="col-md-6 col-sm-12">
        <div class="form-group">
            <div class="col-md-12">
                <egic-label asp-for="@Model.ID_FrontImagePath" style="float:none!important;" />
                <br />
                <egic-editor asp-for="@Model.ID_FrontImagePath" />
                <span asp-validation-for="@Model.ID_FrontImagePath"></span>
            </div>
        </div>
    </div>
    <div class="col-md-6 col-sm-12">
        <div class="form-group">
            <div class="col-md-12">
                <egic-label asp-for="@Model.ID_RearImagePath" style="float:none!important;" />
                <br />
                <egic-editor asp-for="@Model.ID_RearImagePath" />
                <span asp-validation-for="@Model.ID_RearImagePath"></span>
            </div>
        </div>
    </div>
</div>

RamadanBags.Web/Views/Shared/_AddPictures.cshtml
@model PicturesModel
@using EGIC.Core.Models.RamadanBags
@{
    ViewBag.EntityCode = Model.EntityCode;
    ViewBag.UploadButttonID = Model.UploadButttonID;
    ViewBag.ParentModelPicturesCodesProp = Model.ParentModelPicturesCodesProp;
}

<link href="~/lib/fineuploader/fineuploader-4.2.2.min.css" rel="stylesheet" />
<script src="~/lib/fineuploader/jquery.fineuploader-4.2.2.min.js"></script>

<div class="panel panel-default">
    <div class="panel-heading">
        برجاء ادخال صور الرقم القومي 
    </div>
    <div class="panel-body">
        <div class="form-group">
            <div class="col-md-3">
                <egic-label asp-for="PicturesCodes" />
            </div>
            <div class="col-md-9">
                <egic-editor asp-for="PicturesCodes" />
                <span asp-validation-for="PicturesCodes"></span>
            </div>
        </div>
    </div>
</div>

RamadanBags.Web/Views/Shared/_AdminLayout.cshtml
@inject IWorkContext workContext
@using RamadanBags.Services
@using System.Globalization
@{
    var kendoVersion = "2014.1.318";
    var supportRtl = true;


    //avatar
    var currentUser = workContext.CurrentUser;

    //page title
    string adminPageTitle = !string.IsNullOrWhiteSpace(ViewBag.Title) ? $" | {ViewBag.Title}" : "";
    adminPageTitle = $"ايجيك - شنط رمضان{adminPageTitle}";

    //sidebar
    const string hideSidebarAttributeName = "HideSidebar";
    var hideSidebar = currentUser == null;

}
<!DOCTYPE html>
<html @(supportRtl ? Html.Raw(" dir=\"rtl\"") : null)>
<head>
    <title>@adminPageTitle </title>
    <meta http-equiv="Content-type" content="text/html;charset=UTF-8" />
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport" />

    @if (supportRtl)
    {
        <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.rtl.css" />
        <link rel="stylesheet" href="~/lib/adminLTE/AdminLTE-2.3.0.rtl.css" />
        <link rel="stylesheet" href="~/css/admin/styles.rtl.css" />
    }
    else
    {
        <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/lib/adminLTE/AdminLTE-2.3.0.min.css" />
        <link rel="stylesheet" href="~/css/admin/styles.css" />
    }
    <link href="~/css/droid-arabic-kufi.css" rel="stylesheet" />

    <style>
        body, h1, h4, h3, .buttons input {
            font-family: 'DroidKufi-Regular' !important;
            font-weight: normal !important;
            font-style: normal !important;
            /*font-size:inherit;*/
        }

        [data-role="datetimepicker"] {
            text-align: center;
            font-size: small !important;
        }

        .k-grid .k-grid-header .k-header {
            background-color: lightblue;
        }

        .k-grid tbody .k-grid .k-grid-header .k-header {
            background-color: #bcb4b0 !important;
        }

        .k-grid tbody .k-detail-row {
            background-color: #d2d6de !important;
        }

        /* third level grid header */
        .k-grid tbody .k-grid tbody .k-grid .k-grid-header .k-header {
            background-color: #c1c1c1 !important;
        }

        /*
        .k-grid tbody .k-detail-row.k-alt {
            background-color: #cdd0d8!important;
        }
        .k-grid tbody .k-detail-row:hover {
            background-color: #cdd0d8;
        }
        */

    </style>

    <link rel="stylesheet" href="~/lib/adminLTE/skins/_all-skins.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-touchspin/jquery.bootstrap-touchspin.min.css" />
    <link rel="stylesheet" href="~/lib/typeahead/typeahead.css" />
    <link rel="stylesheet" href="~/lib/fontAwesome/css/font-awesome-4.6.3.min.css" />
    <link rel="stylesheet" href="~/lib/jquery-ui-themes/smoothness/jquery-ui-1.10.3.custom.min.css" />
    <link rel="stylesheet" href="~/lib/kendo/@(kendoVersion)/kendo.common.min.css" />
    <link rel="stylesheet" href="~/lib/kendo/@(kendoVersion)/kendo.default.min.css" />

    @if (IsSectionDefined("css"))
    {
        @RenderSection("css")
    }

    <script type="text/javascript" src="~/lib/jquery-1.10.2.min.js"></script>
    <script type="text/javascript" src="~/lib/bootstrap-touchspin/jquery.bootstrap-touchspin.min.js"></script>
    <script type="text/javascript" src="~/lib/bootstrap/bootstrap.min.js"></script>
    <script type="text/javascript" src="~/lib/adminLTE/app.min.js"></script>
    <script type="text/javascript" src="~/lib/jquery.validate.min.js"></script>
    <script type="text/javascript" src="~/lib/jquery.validate.unobtrusive.min.js"></script>
    <script type="text/javascript" src="~/lib/jquery-ui-1.10.3.custom.min.js"></script>
    <script type="text/javascript" src="~/lib/jquery-migrate-1.2.1.min.js"></script>
    <script type="text/javascript" src="~/lib/typeahead/typeahead.bundle.min.js"></script>
    <script type="text/javascript" src="~/js/admin.common.js"></script>
    <script type="text/javascript" src="~/js/admin.navigation.js"></script>
    <script type="text/javascript" src="~/js/admin.search.js"></script>
    <script type="text/javascript" src="~/lib/kendo/@(kendoVersion)/kendo.web.min.js"></script>

    <link rel="shortcut icon" href="~/favicon.ico" type="image/x-icon" />
    <link rel="icon" href="~/favicon.ico" type="image/x-icon" />

</head>
<body class="hold-transition skin-blue @(hideSidebar?" sidebar-collapse":"sidebar-mini") @((ViewBag.miniSidebar!=null && (bool)ViewBag.miniSidebar) ? " sidebar-collapse":"")">
    <div class="throbber">
        <div class="curtain">
        </div>
        <div class="curtain-content">
            <div>
                <h1 class="throbber-header">انتظر...</h1>
                <p>
                    <img src="@Url.Content("~/css/admin/images/throbber-synchronizing.gif")" alt="" />
                </p>
            </div>
        </div>
    </div>
    <div id="ajaxBusy">
        <span>&nbsp;</span>
    </div>
    <div class="wrapper">
        @if (IsSectionDefined("header"))
        {
            @RenderSection("header")
        }
        else
        {
            <div class="main-header">
                <a href="/" class="logo">
                    <!-- mini logo for sidebar mini 50x50 pixels -->
                    <span class="logo-mini"></span>
                    <!-- logo for regular state and mobile devices -->
                    <span class="logo-lg"></span>
                </a>
                <div class="navbar navbar-static-top" role="navigation">
                    @if (!hideSidebar)
                    {
                        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                            <span class="sr-only">&nbsp;</span>
                        </a>
                    }

                    <div class="navbar-custom-menu">
                        <ul class="nav navbar-nav">
                            <li>

                            </li>
                            @if (currentUser != null)
                            {


                                <li class="account-info">
                                    مرحباً, @(string.IsNullOrWhiteSpace(currentUser.FullName) ? currentUser.Username : currentUser.FullName)!
                                </li>
                                <li>
                                    <a asp-controller="Security" asp-action="Logout" asp-area="">خروج</a>
                                </li>
                            }
                            else
                            {
                                <li>
                                    <a asp-controller="Security" asp-action="Login" asp-area="">تسجيل الدخول</a>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
            </div>
        }
        @if (IsSectionDefined("headermenu"))
        {
            @RenderSection("headermenu")
        }
        else if (!hideSidebar)
        {
            <div class="main-sidebar">
                <div class="sidebar">
                    <div class="sidebar-form">
                        <div id="search-box">
                            <input type="text" class="form-control admin-search-box typeahead" placeholder="بحث عن..">
                        </div>
                    </div>
                    <script type="text/javascript">
                        $(document).ready(function () {
                            Admin.Search.init();
                        });
                    </script>
                    @await Html.PartialAsync("Menu", workContext)
                </div>
            </div>
        }
        <div class="content-wrapper">
            @await Html.PartialAsync("Notifications")
            <div>
                @RenderBody()
            </div>
        </div>
        <div class="main-footer clearfix">
            <div class="pull-left">
                برمجة وتنفيذ <a href="#" target="_blank"> شركة ايجيك قسم تكنولوجيا المعلومات</a>
            </div>
            <div class="pull-right hidden-xs">
            </div>
            <div class="text-center">
                @DateTime.Now.ToString("f", new CultureInfo("ar-EG"))
            </div>
        </div>
    </div>

    <script type="text/javascript">
        var AdminLTEOptions = {
            boxWidgetOptions: {
                boxWidgetIcons: {
                    collapse: 'fa-minus',
                    open: 'fa-plus'
                }
            }
        };
    </script>

    <a id="backTop" class="btn btn-back-top bg-teal"></a>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#backTop').backTop();

            $('a.sidebar-toggle').on('click', function () {
                var collapsed = $('body').hasClass('sidebar-collapse');
            });
        });
    </script>

    @if (IsSectionDefined("js"))
    {
        @RenderSection("js")
    }

</body>
</html>

RamadanBags.Web/Views/Shared/_DefaultEmailTemplate.cshtml
@model EmailTemplateModel
@using RamadanBags.Web.Models.EmailTemplates

<style>
    .email-container {
        position: relative;
        width: 100%;
        font-family: Calibri!important;
    }

    .email-bg {
        position: relative;
        z-index: 1;
        height: 100%;
        min-width: 400px;
        max-width: 700px;
        margin: 0 auto;
    }

    .email-center {
        width: 100%;
    }

    @@media screen and (max-width: 400px) {
        .email-center {
            width: 100%;
            overflow: hidden;
            margin: 0 -50px 0 -50px;
        }
    }
</style>

<div style="" class="email-container">
    <div class="email-bg">
        <div class="email-center">
            <p dir="rtl" style="text-align:right;direction:rtl;">
                <span style="">
                    Dears,
                </span>
                <br>
                <br>
                <span style="">
                    @Model.MessageBody
                </span>
            </p>
            @if (!string.IsNullOrWhiteSpace(Model.Url))
            {
                <p dir="ltr" style="text-align:left;direction:ltr;">
                    <a href="@Model.Url">
                        @Model.Url
                    </a>
                </p>
            }
            @if (!string.IsNullOrWhiteSpace(Model.SendFromFullName))
            {
                <p dir="rtl" style="text-align:right;direction:rtl;">
                    <span>
                        Thank you,
                        <br />
                        @(Model.SendFromFullName).
                    </span>
                </p>
            }
            <hr />
        </div>
    </div>
</div>

RamadanBags.Web/Views/Shared/_DeleteButton.cshtml
<span id="btnDelete" class="btn bg-red">
    <i class="fa fa-trash-o"></i>
    حذف
</span>

RamadanBags.Web/Views/Shared/_GridPagerMessages.cshtml
messages: {
    display: "عرض",
    empty: "لا يوجد بيانات",
    page: "صفحة",
    of: "من",
    itemsPerPage: "في كل صفحة",
    first: "الاولي",
    previous: "السابق",
    next: "التالي",
    last: "الاخيره",
    refresh: "تحديث",
    allPages: "الكل",
    morePages: "المزيد"
}

RamadanBags.Web/Views/Shared/_MenuItem.cshtml
@model SiteMapNode

@using EGIC.Web.Framework.Menu
@{
    var supportRtl = true;
    string url = null;
    string controller = Model.ControllerName ?? "";
    string action = Model.ActionName ?? "";
    if (!string.IsNullOrEmpty(Model.ControllerName) && !string.IsNullOrEmpty(Model.ActionName))
    {
        url = Url.Action(Model.ActionName, controller, Model.RouteValues, null, null);
    }
    else if (!string.IsNullOrEmpty(Model.Url))
    {
        url = Model.Url.StartsWith("~/", StringComparison.Ordinal) ? Url.Content(Model.Url) : Model.Url;
    }
    var isActive = url == Context.Request.Path.Value;
    if (!isActive && !string.IsNullOrWhiteSpace(Model.SystemName))
    {
        isActive = Context.Request.Path.Value.Equals($"/{Model.SystemName}/");
    }
}
@if (!string.IsNullOrEmpty(url))
{
    <li class="@(isActive ? "active current-active-item" : "")">
        <a href="@url" class="menu-item-link" @(Model.OpenUrlInNewTab ? Html.Raw(" target=\"_blank\"") : null)>
            @if (!string.IsNullOrEmpty(Model.IconClass))
            {
                <text>
                <i class="fa @Url.Content(Model.IconClass)"></i>
                </text>
            }
            <span class="menu-item-title">@Model.Title</span>
        </a>
    </li>
}
else
{
    <li class="treeview @(isActive ? Html.Raw("active current-active-item") : null)">
        <a href="#">
            @if (!string.IsNullOrEmpty(Model.IconClass))
            {
                <text>
                <i class="fa @Url.Content(Model.IconClass)"></i>
                </text>
            }
            <span>@Model.Title</span>
            @if (supportRtl)
            {
                <i class="fa fa-angle-right pull-right"></i>
            }
            else
            {
                <i class="fa fa-angle-left pull-right"></i>
            }
        </a>
        @{
            var childNodes = Model.ChildNodes.Where(x => x.Visible).ToList();
        }
        @if (childNodes.Any())
        {
            <ul class="treeview-menu">
                @foreach (var childItem in childNodes)
                {
                    @await Html.PartialAsync("_MenuItem", childItem)
                }
            </ul>
        }
    </li>
}

RamadanBags.Web/Views/Shared/_SaveButton.cshtml
<div class="box-footer">
    <button type="submit" name="btn-save" class="btn bg-blue pull-right" id="btn-save">
        <i class="fa fa-floppy-o"></i>
        حفظ
    </button>
</div>